name: Build example app - Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      6.8.2
        host:         windows
        target:       desktop
        arch:         win64_msvc2022_64
        dir:          ${{ github.workspace }}/qt
    - name: Create build directory
      run:  mkdir ${{ github.workspace }}\example\build_example_app
    - name: Download JOM
      uses: suisei-cn/actions-download-file@v1
      with:
        url:    http://download.qt.io/official_releases/jom/jom.zip
        target: ${{ runner.temp }}
    - name: Unzip JOM
      working-directory: ${{ runner.temp }}
      run:  7z x jom.zip -ojom
    - name: cmake
      run: cmake -B ./build_tsblib ./tsblib
    - name: build
      working-directory: ./build_tsblib
      run: cmake --build .
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - name: Build example app
      working-directory: ${{ github.workspace }}/example/build_example_app
      run:  |
            qmake ${{ github.workspace }}\example\TrafficSimulationBasic.pro
            ${{ runner.temp }}\jom\jom -j2
