name: Build tsblib

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -B ./build_tsblib ./tsblib
    - name: build
      working-directory: ./build_tsblib
      run: cmake --build .
