name: Build tsblib - Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -B ${{ github.workspace }}/build_tsblib ${{ github.workspace }}/tsblib
    - name: build
      run: cmake --build ${{ github.workspace }}/build_tsblib -j2
