name: Build tsblib

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOURCE_DIR: ./tsblib
  BUILD_DIR: ./build_tsblib

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 
    - name: cmake
      run: cmake -B $BUILD_DIR $SOURCE_DIR
    - name: make
      working-directory: $BUILD_DIR
      run: make
