name: Build tsblib - Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake gcc
      run: cmake -B ${{ github.workspace }}/build_tsblib_gcc -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ${{ github.workspace }}/tsblib
    - name: build gcc
      run: cmake --build ${{ github.workspace }}/build_tsblib_gcc -j8
    - name: cmake clang
      run: cmake -B ${{ github.workspace }}/build_tsblib_clang -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ${{ github.workspace }}/tsblib
    - name: build clang
      run: cmake --build ${{ github.workspace }}/build_tsblib_clang -j8
