name: Build tsblib - Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: gcc cmake
      run: cmake -B ./build_tsblib_gcc -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ./tsblib
    - name: gcc build
      working-directory: ./build_tsblib_gcc
      run: cmake --build .
    - name: clang cmake
      run: cmake -B ./build_tsblib_clang -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ./tsblib
    - name: clang build
      working-directory: ./build_tsblib_clang
      run: cmake --build .
